// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://piyqgvwzpfbauuocfuxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpeXFndnd6cGZiYXV1b2NmdXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjE3MDgsImV4cCI6MjA2ODU5NzcwOH0.aB451A1lK593TzY8nwTudxFxLBEB6LFeywbAr6L2OWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});